obj-$(CONFIG_IDME)	+= idme.o
obj-$(CONFIG_AMAZON_KLOG_CONSOLE)	+= klog_console.o
obj-$(CONFIG_MDUMP)	+= mdump.o
obj-$(CONFIG_AMAZON_SIGN_OF_LIFE) += sign_of_life.o
obj-$(CONFIG_AMAZON_SIGN_OF_LIFE_MTK) += sign_of_life_mtk.o
